name: trn_bluetooth_manager
description: Bluetooth manager for TRN BT20 device
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_blue_plus: ^1.1.3
  flutter_bluetooth_serial: ^0.4.0
  flutter_localizations:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2
  intl: ^0.17.0
  permission_handler: ^9.2.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
